service: flight-booking-application
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details

plugins:
  - serverless-appsync-plugin
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
  stage: dev
  region: ap-south-1

# you can add statements to the Lambda function's IAM Role here
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:GetItem"
            - "dynamodb:Scan"
          Resource: "arn:aws:dynamodb:#{AWS::Region}:*:table/${self:custom.FLIGHT_BOOKING_APPLICATION_TABLE}"

custom:      
  FLIGHT_BOOKING_APPLICATION_TABLE: flight-booking-application-table

  appSync:
    name: appsync-flight-booking-application
    authenticationType: API_KEY
    mappingTemplates:
      - type: Query
        field: getFlights
        dataSource: getFlightsFunction
        request: false
        response: false
      - type: Mutation
        field: bookFlight
        dataSource: bookFlightFunction
        request: false
        response: false
    dataSources:
      - type: AWS_LAMBDA
        name: getFlightsFunction
        config:
          functionName: getFlights
      
      - type: AWS_LAMBDA
        name: bookFlightFunction
        config:
          functionName: bookFlight

functions:
  getFlights:
    handler: api/getFlights.getAllFlights
    environment:
      FLIGHT_BOOKING_APPLICATION_TABLE: !Ref FlightBookingTable
  
  bookFlight:
    handler: api/bookFlight.bookFlight
    environment:
      FLIGHT_BOOKING_APPLICATION_TABLE: !Ref FlightBookingTable

resources:
  Resources:
    FlightBookingTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.FLIGHT_BOOKING_APPLICATION_TABLE}